import { useCallback } from 'react'
import { useLanguage } from '../../contexts/LanguageContext'

// UI copy only. Trading symbols, API values and model output stay unchanged.
export const terminalChinese: Record<string, string> = {
  'Current direction': '当前方向',
  'Direction history': '方向历史',
  Heatmap: '热力图',
  unavailable: '不可用',
  'All positions closed': '全部持仓已平仓',
  'Long liquidations can force sell into downside breaks.':
    '价格向下突破时，多头清算可能引发强制卖出。',
  'Short liquidations can force buy into upside breaks.':
    '价格向上突破时，空头清算可能引发强制买入。',
  'Failed to fetch kline data': '获取 K 线数据失败',
  'Failed to load chart data': '加载图表数据失败',
  'BB Upper': '布林上轨',
  'BB Middle': '布林中轨',
  'BB Lower': '布林下轨',
  '{count} cyc': '{count} 轮',
  '{count} actions': '{count} 个动作',
  '{count} action': '{count} 个动作',
  'buy {buy}% / sell {sell}%': '买入 {buy}% / 卖出 {sell}%',
  '{value}% win': '胜率 {value}%',
  'edge concentrates in holds ≥ 1h ({long} vs {short} under 1h)':
    '持仓至少 1 小时的收益更高（{long}，不足 1 小时为 {short}）',
  'short holds outperform on this sample ({short} vs {long} ≥ 1h)':
    '本组样本中短线持仓收益更高（{short}，至少 1 小时为 {long}）',
  'Market-close {symbol} {side}?': '以市价平掉 {symbol} {side}持仓？',
  '{symbol} {side} closed': '{symbol} {side}持仓已平仓',
  'Market-close ALL {count} open positions?': '以市价平掉全部 {count} 个持仓？',
  '{failed}/{count} closes failed': '{failed}/{count} 个持仓平仓失败',
  'AI fee wallet is low ({balance} USDC) — top up soon.':
    'AI 费用钱包余额不足（{balance} USDC），请及时充值。',
  'Close {symbol}': '平仓 {symbol}',
  'click to switch': '点击切换',
  avg: '平均',
  peak: '最高',
  cap: '上限',
  'Long bias': '偏多',
  'Short bias': '偏空',
  'Neutral bias': '中性',
  'details ready': '详情已就绪',
  Price: '价格',
  '{count} active price bins returned.': '已返回 {count} 个有效价格分桶。',
  '{count} symbols fixed; trade only these.':
    '已固定 {count} 个品种，仅交易这些品种。',
  '{count} selected': '已选择 {count} 个',
  'Without manual picks, runtime uses Claw402.ai Top {count} in this range':
    '未手动选择时，运行时使用该范围内 Claw402.ai 排名前 {count} 个品种',
  open_long: '开多',
  open_short: '开空',
  close_long: '平多',
  close_short: '平空',
  wait: '等待',
  LONG: '多头',
  SHORT: '空头',
  'Flush fuel below': '下方下跌动力',
  'Squeeze fuel above': '上方逼空动力',
  'Bin step': '价格分桶间距',
  'Long liq': '多头清算',
  'Short liq': '空头清算',
  Eq: '权益',
  Kline: 'K 线',
  'Search symbol...': '搜索品种…',
  Sym: '品种',
  Go: '确认',
  'Cycle #': '轮次 #',
  'O:': '开：',
  'H:': '高：',
  'L:': '低：',
  'C:': '收：',
  'V(': '量(',
  Vol: '成交量',
  'B/S': '买/卖',
  H: '最高',
  L: '最低',
  S: '卖',
  OK: '确认',
  'Failed to load strategies': '加载策略失败',
  'Symbol list unavailable': '品种列表不可用',
  'Claw402.ai board unavailable': 'Claw402.ai 榜单不可用',
  'Failed to create strategy': '创建策略失败',
  'Failed to save strategy': '保存策略失败',
  'Failed to activate strategy': '启用策略失败',
  'Failed to delete strategy': '删除策略失败',
  'NOFX Autopilot started': 'NOFX 自动交易已启动',
  'Autopilot uses the live Claw402 board by default.':
    '自动交易默认使用 Claw402 实时榜单。',
  ready: '已就绪',
  'no action': '无操作',
  '○ sync': '○ 同步中',
  '○ down': '○ 未连接',
  'Close failed': '平仓失败',
  'Close all': '全部平仓',
  '(Test Mode)': '（测试模式）',
  'Loading...': '正在加载…',
  'Binance Kline Data': 'Binance K 线数据',
  klines: '根 K 线',
  'Historical Order Data': '历史订单数据',
  orders: '个订单',
  Status: '状态',
  '✅ Data fetched successfully, chart component in development':
    '数据获取成功，图表组件开发中',
  'Candlestick chart': 'K 线图',
  'No closed trades yet.': '暂无已平仓交易。',
  'trades ·': '笔交易 ·',
  '· fees $': '· 手续费 $',
  last: '最近',
  'closed ·': '笔已平仓 ·',
  'Execution log': '执行日志',
  'Execution log · AI decisions & fills per cycle':
    '执行日志 · 每轮 AI 决策与成交',
  'No execution events yet.': '暂无执行记录。',
  CYCLE: '轮次',
  FAULT: '故障',
  conf: '置信度',
  ok: '成功',
  throttle: '冷却限制',
  risk: '风险',
  'No net-flow data (claw402 payment required).':
    '暂无净流入数据（需要 claw402 支付）。',
  SYMBOL: '品种',
  NET: '净流入',
  'BUY/SELL': '买入/卖出',
  TRADES: '成交笔数',
  PRICE: '价格',
  'net inflow =': '净流入 =',
  'net buying ·': '净买入 ·',
  green: '绿色',
  red: '红色',
  '= buy/sell split': '= 买卖占比',
  'trades = count · last price = last traded price':
    '成交笔数 = 交易次数 · 最新价 = 最近成交价',
  '· Live candles': '· 实时 K 线',
  'bars ·': '根 K 线 ·',
  'Loading market…': '正在加载行情…',
  'Cost / Liq map': '成本 / 清算图',
  '· Cost line': '· 成本线',
  liq: '清算',
  mark: '标记价',
  'positions /': '个持仓 /',
  'liq levels': '个清算价位',
  'No cost/liq heatmap for': '暂无成本/清算热力图：',
  '(crypto / main-dex markets have none).':
    '（加密货币 / 主交易所市场暂无数据）。',
  'Loading cost/liquidation map…': '正在加载成本/清算图…',
  'Cost line': '成本线',
  'Decision funnel matrix: flow, signal, decision, execute, hold':
    '决策漏斗矩阵：资金流、信号、决策、执行、持仓',
  'Order book': '订单簿',
  'Connecting to Hyperliquid…': '正在连接 Hyperliquid…',
  price: '价格',
  size: '数量',
  'cum $': '累计金额 $',
  spread: '价差',
  bps: '基点',
  B: '买',
  '% S': '% 卖',
  'No live risk data.': '暂无实时风险数据。',
  'Risk radar': '风险雷达',
  'Risk radar · live position-risk check': '风险雷达 · 实时持仓风险监测',
  long: '多头',
  short: '空头',
  net: '净值',
  'No signal data (claw402).': '暂无信号数据（claw402）。',
  'click to switch ▸': '点击切换 ▸',
  signals: '个信号',
  'Signal matrix': '信号矩阵',
  'Signal matrix · vergex': '信号矩阵 · Vergex',
  Bullish: '看多',
  Bearish: '看空',
  Neutral: '中性',
  bullish: '看多',
  bearish: '看空',
  neutral: '中性',
  'Close position': '平仓',
  'Flatten book': '全部平仓',
  'toggle presentation mode': '切换演示模式',
  orchestration: '交易编排',
  cycle: '轮次',
  'Your AI is live.': 'AI 已启动。',
  'It reads the whole market before acting — the first decision usually lands within a minute or two and will appear in the Execution Log below. You can stop it anytime from the Config page.':
    'AI 会先分析全市场，通常一两分钟内做出首次决策，并显示在下方执行日志中。你可以随时在配置页停止运行。',
  model: '模型',
  strategy: '策略',
  lev: '杠杆',
  scan: '扫描',
  m: '分钟',
  universe: '候选品种',
  positions: '持仓',
  'next cycle': '下一轮',
  Equity: '账户权益',
  'Total P/L · incl. unrealized': '总盈亏 · 含未实现',
  'Realized P/L · closed trades': '已实现盈亏 · 已平仓',
  'Profit factor': '盈利因子',
  'Max drawdown': '最大回撤',
  trades: '交易',
  win: '盈利',
  loss: '亏损',
  gross: '毛收益',
  fees: '手续费',
  'sharpe/trade': '每笔夏普比率',
  'avg win/loss': '平均盈亏',
  'Orchestration topology': '交易编排拓扑',
  'Orchestration topology · net inflow → signal → execute → hold':
    '交易编排拓扑 · 净流入 → 信号 → 执行 → 持仓',
  FLOW: '资金流',
  SIGNAL: '信号',
  DECISION: '决策',
  EXECUTE: '执行',
  HOLD: '持仓',
  Positions: '持仓',
  'Current positions · live': '当前持仓 · 实时',
  open: '笔持仓',
  symbol: '品种',
  'side·lev': '方向·杠杆',
  entry: '开仓价',
  PnL: '盈亏',
  'return%': '收益率%',
  'No open positions.': '暂无持仓。',
  'Recent trades': '最近交易',
  'Recent closes · symbol/side/hold/pnl': '最近平仓 · 品种/方向/持仓时长/盈亏',
  side: '方向',
  hold: '持仓时长',
  closed: '平仓时间',
  'Market net inflow': '市场净流入',
  'Market net inflow ·': '市场净流入 ·',
  markets: '个市场',
  'By symbol': '品种统计',
  'By-symbol history · trades/win/pnl': '品种历史 · 交易/胜率/盈亏',
  '% win': '% 胜率',
  'No symbol history.': '暂无品种历史。',
  'Edge profile': '收益分布',
  'Net by hold time & side · after fees':
    '按持仓时长与方向统计净收益 · 扣除手续费',
  '● running': '● 运行中',
  '○ stopped': '○ 已停止',
  'closing…': '正在平仓…',
  'close all': '全部平仓',
  close: '平仓',
  'AI fee wallet is out of USDC — decisions are failing.':
    'AI 费用钱包的 USDC 已耗尽，决策调用失败。',
  'Safe mode: AI failed repeatedly, no new positions are being opened.':
    '安全模式：AI 连续调用失败，已暂停开新仓。',
  'Deposit Base USDC to the Claw402 wallet, the trader recovers automatically.':
    '向 Claw402 钱包充值 Base 网络 USDC 后，交易员会自动恢复。',
  Flat: '空仓',
  'Long-lean': '偏多',
  'Short-lean': '偏空',
  Balanced: '均衡',
  Risky: '高风险',
  High: '偏高',
  Safe: '安全',
  Tight: '紧张',
  Ample: '充足',
  Concentrated: '集中',
  Spread: '分散',
  Calm: '平稳',
  Deep: '较深',
  Caution: '注意',
  Full: '已满',
  Room: '有余量',
  '● live': '● 实时',
  '○ flat': '○ 空仓',
  'Net exposure': '净敞口',
  Leverage: '杠杆',
  'Margin used': '已用保证金',
  Concentration: '集中度',
  Drawdown: '回撤',
  'Unrealized PnL': '未实现盈亏',
  'of equity': '占账户权益',
  'top-position share': '最大持仓占比',
  'peak drawdown': '历史最大回撤',
  'held / cap': '已持仓 / 上限',
  Account: '账户',
  'AI Models': 'AI 模型',
  Exchanges: '交易所',
  Settings: '设置',
  Email: '邮箱',
  'Change Password': '修改密码',
  'New Password': '新密码',
  'At least 8 characters': '至少 8 个字符',
  'Add Model': '添加模型',
  'No AI models configured yet': '尚未配置 AI 模型',
  'Add Exchange': '添加交易所',
  'No exchange accounts connected yet': '尚未连接交易所账户',
  Balance: '余额',
  Available: '可用余额',
  'Balance unavailable:': '无法获取余额：',
  'Connect a Telegram bot to receive trading notifications and interact with your traders.':
    '连接 Telegram 机器人，接收交易通知并与交易员交互。',
  'Configure Telegram Bot': '配置 Telegram 机器人',
  'Failed to load exchange balances': '加载交易所余额失败',
  'Failed to load AI models': '加载 AI 模型失败',
  'Failed to load exchanges': '加载交易所失败',
  'Password must be at least 8 characters': '密码必须至少包含 8 个字符',
  'Failed to update password': '更新密码失败',
  'Password updated successfully': '密码更新成功',
  'Model not found': '未找到模型',
  'Model config saved': '模型配置已保存',
  'Failed to save model config': '保存模型配置失败',
  'Model config removed': '模型配置已移除',
  'Failed to remove model config': '移除模型配置失败',
  'Hyperliquid must be connected through wallet authorization, not manual keys.':
    'Hyperliquid 必须通过钱包授权连接，不能手动填写密钥。',
  'Exchange config updated': '交易所配置已更新',
  'Exchange account created': '交易所账户已创建',
  'Failed to save exchange config': '保存交易所配置失败',
  'Exchange account deleted': '交易所账户已删除',
  'Failed to delete exchange account': '删除交易所账户失败',
  'Updating...': '正在更新…',
  'Update Password': '更新密码',
  'Custom Model': '自定义模型',
  'Base URL': '接口地址',
  'API Key': 'API 密钥',
  Secret: '密钥',
  Passphrase: '口令',
  Wallet: '钱包',
  'Aster Key': 'Aster 密钥',
  'Lighter Key': 'Lighter 密钥',
  Active: '已启用',
  Inactive: '未启用',
  'Refreshing…': '正在刷新…',
  'Refresh Balances': '刷新余额',
  'Long Bias': '偏多',
  'Short Bias': '偏空',
  'Bull/Bear Radar has not loaded yet.': '多空雷达尚未加载。',
  'Bull/Bear Radar': '多空雷达',
  '· stable since': '· 稳定始于',
  'Direction changes': '方向变更',
  'No direction-change history returned.': '暂无方向变更历史。',
  Mark: '标记价',
  'Cost/liquidation heatmap has not loaded yet.': '成本/清算热力图尚未加载。',
  'Cost / Liquidation Heatmap': '成本 / 清算热力图',
  'position cost distribution · liquidation clusters':
    '持仓成本分布 · 清算聚集区',
  'cost positions': '个成本持仓',
  'liquidation prices': '个清算价位',
  'Liquidation prices use latest snapshot; incremental trades can lag.':
    '清算价格来自最新快照；增量交易可能存在延迟。',
  live: '实时',
  'Long cost': '多头成本',
  'Short cost': '空头成本',
  'Long liquidation': '多头清算',
  'Short liquidation': '空头清算',
  'Signal Board': '信号榜单',
  'Live direction board · direction history · liquidation map':
    '实时方向榜单 · 方向历史 · 清算图',
  'Symbol pool': '品种池',
  Refresh: '刷新',
  'Clear selected': '清空选择',
  'Follow Claw402.ai board dynamically': '动态跟随 Claw402.ai 榜单',
  'At runtime, trade the current range Top': '运行时交易当前范围内排名前',
  '; the board refreshes each cycle.': '的品种；每轮刷新榜单。',
  'Pinned universe': '固定品种池',
  Top: '前',
  'Load Signal Board': '加载信号榜单',
  mainnet: '主网',
  '% band': '% 区间',
  'Loading direction history and heatmap...': '正在加载方向历史和热力图…',
  'NOFX Autopilot follows the Claw402 direction board and uses liquidation structure and raw candles as context.':
    'NOFX 自动交易跟随 Claw402 方向榜单，结合清算结构与原始 K 线分析。',
  'No Claw402 markets available.': '暂无可用的 Claw402 市场。',
  'No markets available.': '暂无可用市场。',
  'Load Claw402 board': '加载 Claw402 榜单',
  'Claw402 board': 'Claw402 榜单',
  'AI Model:': 'AI 模型：',
  'Exchange:': '交易所：',
  'Strategy:': '策略：',
  'Cycles:': '轮次：',
  'Runtime:': '运行时长：',
  min: '分钟',
  'SYSTEM_STATUS::ONLINE': '系统状态::在线',
  'LAST_UPDATE::': '最后更新::',
  'EQ::': '权益::',
  'PNL::': '盈亏::',
  'All Claw402': '全部 Claw402',
  'US Stocks': '美股',
  Crypto: '加密货币',
  Commodities: '大宗商品',
  Indices: '指数',
  FX: '外汇',
  'Pre-IPO': '上市前资产',
  Careful: '谨慎',
  'Fewer trades, only aligned signals': '减少交易，仅在信号一致时入场',
  'Recommended balance of opportunity and risk': '兼顾机会与风险的推荐配置',
  'Faster trend capture with more positions': '更快捕捉趋势，支持更多持仓',
  'NOFX Claw402 Auto Strategy': 'NOFX Claw402 自动策略',
  'The single built-in strategy: read the Claw402.ai board, fetch per-symbol details, then trade with raw candles.':
    '内置策略：读取 Claw402.ai 榜单，获取各品种详情，结合原始 K 线交易。',
  'Strategy saved and activated': '策略已保存并启用',
  'Strategy saved': '策略已保存',
  'Strategy activated': '策略已启用',
  'Delete this strategy?': '删除此策略？',
  'Confirm delete': '确认删除',
  Delete: '删除',
  Cancel: '取消',
  'Strategy deleted': '策略已删除',
  'NOFX Autopilot': 'NOFX 自动交易',
  'Autonomous market selection powered by the live Claw402.ai direction board.':
    '根据 Claw402.ai 实时方向榜单自动选择交易市场。',
  'Launch Autopilot': '启动自动交易',
  'My strategies': '我的策略',
  'One-line strategy note': '一句话策略备注',
  'Unsaved changes': '有未保存的更改',
  'Save and use': '保存并使用',
  Save: '保存',
  'Activate only': '仅启用',
  'Advanced settings': '高级设置',
  'Trading style': '交易风格',
  'Raw candles': '原始 K 线',
  Timeframe: '时间周期',
  Bars: 'K 线数量',
  'Trading parameters': '交易参数',
  'Max positions': '最大持仓数',
  'Entry confidence': '入场置信度',
  'Strategy note': '策略备注',
  'Example: only trade clean trends; skip entries when board signals conflict with candles.':
    '例如：仅交易明确趋势；榜单信号与 K 线冲突时跳过入场。',
  'Initialize Autopilot': '初始化自动交易',
  'Beginner Guard': '新手保护',
  'Your wallet is ready': '你的钱包已准备就绪',
  'Pay per call': '按次付费',
  'Preparing your Base wallet...': '正在准备你的 Base 钱包…',
  'Deposit address (Base USDC)': '充值地址（Base 网络 USDC）',
  'Refresh balance': '刷新余额',
  'Wallet address': '钱包地址',
  Address: '地址',
  'Copy address': '复制地址',
  'Private key, back it up now': '私钥，请立即备份',
  'Private key': '私钥',
  'Copy private key': '复制私钥',
  Skip: '跳过',
  'Copy failed': '复制失败',
  'Failed to prepare beginner wallet': '准备新手钱包失败',
  'Continue setup': '继续设置',
  'This wallet only pays for model calls. It does not fund your exchange automatically. The private key cannot be recovered, and you should only deposit Base USDC.':
    '此钱包仅支付模型调用费用，不会自动向交易所转账。私钥无法恢复，请仅充值 Base 网络 USDC。',
  FAQ: '常见问题',
  'Clear search': '清空搜索',
  'Still have questions?': '还有疑问？',
  'Ask in the community or open an issue — both are answered by the people building NOFX.':
    '在社区提问或提交 Issue，NOFX 开发团队会为你解答。',
  'Telegram community': 'Telegram 社区',
  'Search FAQ...': '搜索常见问题…',
  SIGNAL_LOST: '页面未找到',
  'The requested coordinates do not exist in the current sector. The page may have been moved, deleted, or never existed in this timeline.':
    '请求的页面不存在，可能已被移动或删除。',
  RETURN_BASE: '返回首页',
}

export function useUiLanguage() {
  const { language } = useLanguage()
  return useCallback(
    (english: string, values?: Record<string, string | number>) => {
      const translated =
        language === 'zh' ? (terminalChinese[english] ?? english) : english
      return values
        ? translated.replace(/\{(\w+)\}/g, (placeholder, key: string) =>
            values[key] === undefined ? placeholder : String(values[key])
          )
        : translated
    },
    [language]
  )
}
